server:
  port: 9090

spring:
  application:
    name: Kaddem

  datasource:
    url: jdbc:mysql://localhost:3306/kaddem
    username:
      root
    password:
    driver-class-name:
       com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL Dialect
        validator.apply_to_ddl: true
